# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0002_auto_20180423_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantesmodel',
            name='Apellidos',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participantesmodel',
            name='CargoEmpresa',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participantesmodel',
            name='Celular',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participantesmodel',
            name='Ciudad',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participantesmodel',
            name='Direccion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participantesmodel',
            name='FechaNacimiento',
            field=models.DateField(default='2018-04-23'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participantesmodel',
            name='Identificicacion',
            field=models.CharField(default=1, max_length=25, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participantesmodel',
            name='NITEmpresa',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participantesmodel',
            name='Nombres',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participantesmodel',
            name='Sexo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Femenino'), (2, 'Masculino')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participantesmodel',
            name='TipoDocumento',
            field=models.PositiveSmallIntegerField(choices=[(1, 'C\xe9dula de Ciudadan\xeda'), (2, 'C\xe9dula de Extranjer\xeda'), (3, 'Pasaporte')], default=1),
            preserve_default=False,
        ),
    ]
