# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0003_auto_20180423_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantesmodel',
            name='Apellidos',
        ),
        migrations.RemoveField(
            model_name='participantesmodel',
            name='Nombres',
        ),
    ]
