# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0004_auto_20180423_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantesmodel',
            name='Celular',
            field=models.CharField(max_length=15),
        ),
    ]
