# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 18:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0005_auto_20180424_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaseGruposUsuariosModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaPartido', models.DateField()),
                ('Grupo', models.CharField(max_length=10)),
                ('Equipo1', models.CharField(max_length=50)),
                ('Equipo2', models.CharField(max_length=50)),
                ('MarcadorEquipo1', models.IntegerField()),
                ('MarcadorEquipo2', models.IntegerField()),
                ('Participante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblFaseGruposUsuarios',
            },
        ),
        migrations.AlterUniqueTogether(
            name='fasegruposusuariosmodel',
            unique_together=set([('Grupo', 'Equipo1', 'Equipo2', 'Participante')]),
        ),
    ]
