# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0006_auto_20180425_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasegruposusuariosmodel',
            name='FechaRegistro',
            field=models.DateTimeField(auto_now_add=True, default='2018-01-01'),
            preserve_default=False,
        ),
    ]
