# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 12:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0008_auto_20180425_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablasPosocionesUsuariosModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grupo', models.CharField(max_length=10)),
                ('Equipo', models.CharField(max_length=50)),
                ('PartidoJugados', models.IntegerField()),
                ('Ganados', models.IntegerField()),
                ('Empatados', models.IntegerField()),
                ('Perdidos', models.IntegerField()),
                ('GolaFavor', models.IntegerField()),
                ('GolContra', models.IntegerField()),
                ('GolDiferencia', models.IntegerField()),
                ('Puntos', models.IntegerField()),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('Participante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblTablasPosocionesUsuarios',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tablasposocionesusuariosmodel',
            unique_together=set([('Grupo', 'Equipo', 'Participante')]),
        ),
    ]
