# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0011_auto_20180426_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='faseoctavosusuariosmodel',
            name='Identificador',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faseoctavosusuariosmodel',
            name='PenalEquipo1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faseoctavosusuariosmodel',
            name='PenalEquipo2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
