# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0012_auto_20180426_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faseoctavosusuariosmodel',
            old_name='PenalEquipo1',
            new_name='PenalEquipoGanador',
        ),
        migrations.RemoveField(
            model_name='faseoctavosusuariosmodel',
            name='PenalEquipo2',
        ),
    ]
