# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 23:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0016_auto_20180427_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaseGruposAdminModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaPartido', models.DateField()),
                ('Grupo', models.CharField(max_length=10)),
                ('Equipo1', models.CharField(max_length=50)),
                ('MarcadorEquipo1', models.IntegerField()),
                ('Equipo2', models.CharField(max_length=50)),
                ('MarcadorEquipo2', models.IntegerField()),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('Participante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblFaseGruposAdmin',
            },
        ),
        migrations.CreateModel(
            name='RankingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PuntajeFaseGrupos', models.IntegerField()),
                ('PuntajeOctavos', models.IntegerField()),
                ('PuntajeCuartos', models.IntegerField()),
                ('PuntajeSeminFinales', models.IntegerField()),
                ('PuntajeFinal', models.IntegerField()),
                ('Puntaje', models.IntegerField()),
                ('Participante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblRankingUsuarios',
            },
        ),
        migrations.AlterUniqueTogether(
            name='rankingmodel',
            unique_together=set([('Participante',)]),
        ),
        migrations.AlterUniqueTogether(
            name='fasegruposadminmodel',
            unique_together=set([('Grupo', 'Equipo1', 'Equipo2', 'Participante')]),
        ),
    ]
