# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0017_auto_20180430_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingmodel',
            name='PuntajeCuartos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankingmodel',
            name='PuntajeFaseGrupos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankingmodel',
            name='PuntajeFinal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankingmodel',
            name='PuntajeOctavos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankingmodel',
            name='PuntajeSeminFinales',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
