# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0018_auto_20180501_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingmodel',
            name='FechaModifica',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='rankingmodel',
            name='FechaRegistro',
            field=models.DateTimeField(auto_now_add=True, default='2018-05-01'),
            preserve_default=False,
        ),
    ]
