# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-02 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0024_auto_20180502_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingmodel',
            name='PuntajeCuartos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rankingmodel',
            name='PuntajeFaseGrupos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rankingmodel',
            name='PuntajeFinal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rankingmodel',
            name='PuntajeOctavos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rankingmodel',
            name='PuntajeSeminFinales',
            field=models.IntegerField(default=0),
        ),
    ]
