# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-07 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0025_auto_20180502_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participantesmodel',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='participantesmodel',
            unique_together=set([('email',)]),
        ),
    ]
